site_name: User-Friendly Pipeline to Recognize Emotions with Movement Data
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

nav:
  - Getting Started: index.md
  # - Getting Started: gettingstarted.md
  - Config: config.md
  - Pipelines: 
    - Combine Dataframes: pipelines_combine_dataframes.md
    - Feature Extraction: pipelines_feature_extraction.md
    - Train Model: pipelines_train_model.md
    - End To End: pipelines_complete_pipeline.md
    - Classify Movement Data: pipelines_classifying_data.md
  - Classes:
    - Import Data: classes_import_data.md
    - Create Combined Dataframe: classes_create_combined_dataframe.md
    - Low-Pass Filter: classes_lowpass_filter.md
    - Scale Data: classes_scalexyz_data.md
    - Extract Features: classes_extract_features.md
    - Principal Component Analysis (PCA): classes_pca_handler.md
    - Train Model: classes_train_model.md
    - Classify Movement Data: classes_classify_movement_data.md
  - Other: other.md



copyright: |
  &copy; 2023 <a href="https://github.com/mininato"  target="_blank" rel="noopener">Anh-Duc Duong</a>